-- set echo on;

begin

ERR_LOG_PKG.SAV_ERR_TYPE(106800, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'General ASSIGNMENT_DELIVERY_SERVICE error', 'Y' );

ERR_LOG_PKG.SAV_ERR_TYPE(106801, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Custom Setting Error', 'Y' );

ERR_LOG_PKG.SAV_ERR_TYPE(106802, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Handler Class Not Found Error', 'Y' );

ERR_LOG_PKG.SAV_ERR_TYPE(106803, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error while creating instance of Handler Class', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106804, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Illigal Access Error for Handler Class', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106805, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'File Archieve error while archiving the MCF file', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106806, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'App Log Error', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106807, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'BMS to MIE conversion Error', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106808, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Invalid UserInfo Error', 'Y' );

ERR_LOG_PKG.SAV_ERR_TYPE(106809, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'JNDI Lookup Error', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106810, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'EJB Create Error', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106811, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE','Remote Invocation Error', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106812, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Template File not found Error', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106813, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Setting not found Error', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106814, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'MitchellEnvelope does not contain CIECA Document', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106815, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Invalid ARC5 Delivery Directory', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106816, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'No UserInfo ECM Appl Access Code', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106817, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error Getting CIECA BMS Doc From MitchellEnvelope', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106818, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error Renaming MIE File For ARU Pickup', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106819, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error Unmarshaling MIE File', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106820, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Missing Second Estimate in MIE File', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106821, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error Creating ARC5 MIE File', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106822, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error Copying ARC5 MIE File', 'Y');

-- New Error Codes for Jetta/SIP 3.5 (Nov-2009)
--
ERR_LOG_PKG.SAV_ERR_TYPE(106823, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'MitchellEnvelope does not contain a valid AdditionalAppraisalAssignmentInfo Document', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106824, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Incomplete ADS Context provided for submitting an ECM Cancel Alert', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106825, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error retrieving Document or Attachment from DocStore', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106826, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error sending Shop Supplement Email Notification.', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106827, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error adding File Attachment Object to MCF package.', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106828, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error retrieving Shop Supplement(Text) Request doc.', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106829, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error sending Shop Supplement FAX Notification.', 'Y');

-- New Error Codes for Supplement Capture Project (Q1-2010)
--
ERR_LOG_PKG.SAV_ERR_TYPE(106830, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error writing APP LOG.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106831, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error gathering Work Process Keys', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106832, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error extracting user info and work process envelope.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106833, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error adding CIECA to outbound envelope.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106834, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error adding attachments to outbound envelope.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106835, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error during depencendy and sanity check.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106836, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error removing private keys.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106837, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error processing update work process message.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106838, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error processing work process init message.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106839, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error posting to message bus.', 'Y');

-- New Error Codes for Assignment Email
-- 106840 is already taken in the code in AbstractMsgBusDelHndlr, although it is not registered here.
-- Now add it. Shawn Song 07/20/2012
ERR_LOG_PKG.SAV_ERR_TYPE(106840, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error in App Logging.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106841, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error in XSLT transforming.', 'Y');

ERR_LOG_PKG.SAV_ERR_TYPE(106842, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error in sending assignment email.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106843, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error in sending estimate upload success email.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106844, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error in sending estimate upload fail email.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106845, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error in sending non-drp shop supp email.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106846, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'No Email for user.', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106847, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error in sending assignment fax.', 'Y');



ERR_LOG_PKG.SAV_ERR_TYPE(106848, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error Getting Culture from DataBase', 'Y');
ERR_LOG_PKG.SAV_ERR_TYPE(106849, 'PARTIALLOSS', 'ASSIGNMENT_DELIVERY_SERVICE', 'Error in getting Resource Bundle', 'Y');


end;
/
