-- adding a new value RCCOnnect in the 
-- Group: PARTIALLOSS_SIP_ASSIGNMENT_DELIVERY_SETTINGS
-- Setting: PARTIALLOSS_SIP_ASSIGNMENT_DELIVERY_DESTINATION

 BEGIN
             EPD_CUSTOMSETTINGS_UTILITY_PKG.PUT_EPD_EXP_VALUE_LIST('DBACUS',  upper('ECM_MCFXML_LIST'),'ECLAIM_MCFXML;ARC5;ARC7;RCCONNECT',
             upper('ECM_MCFXML_LIST'),'ECM_MCFXML_LIST', '1',NULL);

             EPD_CUSTOMSETTINGS_UTILITY_PKG.PUT_EPD_EXP_VALUE_LIST('DBACUS',  upper('ECM_MCFXML_LIST'),'ECLAIM_MCFXML;ARC5;ARC7;RCCONNECT',
             upper('ARC5'),'ARC5', '2',NULL);
             
              EPD_CUSTOMSETTINGS_UTILITY_PKG.PUT_EPD_EXP_VALUE_LIST('DBACUS',  upper('ECM_MCFXML_LIST'),'ECLAIM_MCFXML;ARC5;ARC7;RCCONNECT',
             upper('ARC7'),'ARC7', '3',NULL);

             EPD_CUSTOMSETTINGS_UTILITY_PKG.PUT_EPD_EXP_VALUE_LIST('DBACUS',  upper('ECM_MCFXML_LIST'),'ECLAIM_MCFXML;ARC5;ARC7;RCCONNECT',
             upper('RCCONNECT'),'RCCONNECT', '4',NULL);
             
             epd_extended_properties_pkg.put_value_list_to_prop('PARTIALLOSS_SIP_ASSIGNMENT_DELIVERY_DESTINATION','ECM_MCFXML_LIST');
             COMMIT;
end;
             /
      
